site_name: order.
site_url: https://michaeldougal.github.io/order
repo_name: order
repo_url: https://github.com/michaeldougal/order
theme:
  name: material
  logo: icon_square.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
nav:
    - Home: 'index.md'
    - Getting started: 'gettingstarted.md'
    - Rules: 'rules.md'
    - API: 'api.md'
    - Included modules: 'included.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences