site_name: order.
site_url: https://michaeldougal.github.io/order
repo_name: order
repo_url: https://github.com/michaeldougal/order
theme:
  name: material
  logo: icon_square.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
nav:
    - Home: 'index.md'
    - Getting started: 'gettingstarted.md'
    - API: 'api.md'
    - Special notes: 'notes.md'
    - Contributions: 'contributions.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/chiefwildin
    - icon: fontawesome/brands/github
      link: https://github.com/michaeldougal/order
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QvZ66Pw
copyright: Copyright &copy; 2023 - Michael Dougal