site_name: Michael Dougal
site_url: https://michaeldougal.github.io/
nav:
    - Home: index.md
    - About: about.md
theme:
  name: material
  logo: icon.svg
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode